### ISSUE TITLE
Proper formatting of CSS

### ISSUE THREAD

**Issue by farishkash** [ney17/prj-rev-bwfs-tea-cozy#6]
CSS blocks are meant to be written with clear indication of were they start and were they end. 

You write the css selector then the bracket { and drop it down to the next line to start.  Same with the closing bracket }  It should be by itself.  This makes it easier to find errors and mistakes as everything is separated which makes it easier to read. 

Also you do not write css on one line either as it makes it difficult to read.

Your css

```
header{display: flex;
justify-content: space-between;
border-bottom: 1px solid seashell;
position: fixed;
width: 100%;
height: 69px;
background-color: black;
z-index: 1;}

.logo img{padding-left: 10px; padding-right: 50px;}
```

How it should be properly written and formatted.

```
header{
display: flex;
justify-content: space-between;
border-bottom: 1px solid seashell;
position: fixed;
width: 100%;
height: 69px;
background-color: black;
z-index: 1;
}

.logo img{
padding-left: 10px; 
padding-right: 50px;
}
```

**Comment by ney17** [comment]
Thank you, noted and that is very helpful coz when grows it is easier to get lost.
