### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [ney17/prj-rev-bwfs-tea-cozy#8]
Needs Improvement.  The site is not aligned correctly.  The css needs to be written to center the site so it looks closer to spec.

As I mention in the issues the majority of the problems are in the css.  

You also need to fix the tea of the month area because you have the text to the side of it.

**Comment by ney17** [comment]
I had difficulties in aligning the text in tea of the month, i tried to consult on slack but i didn't get more helpful solution.
